### ISSUE TITLE
Readme.md needs updating with NAB instructions

### ISSUE THREAD

**Issue by rcrowder** [numenta/nupic.regression#31]
The included NAB tests fail fast if NAB environment variable is not setup, and pointing to a NAB clone directory.

**Comment by rcrowder** [comment]
With NAB installed, and NAB env variable setup, the following Gist shows the output from a Windows run - https://gist.github.com/rcrowder/21ab5bb72525741b12ff

**Comment by rhyolight** [comment]
@BoltzmannBrain Can you please do this?

**Comment by BoltzmannBrain** [comment]
Will do, I'll take a look this weekend.
