### ISSUE TITLE
NAB regression test failing

### ISSUE THREAD

**Issue by SaganBolliger** [numenta/nupic.regression#34]
The NAB regression test [has failed](https://travis-ci.org/numenta/nupic.regression/builds/97590749). The new scores are uniformly better than the old scores.

My understanding is that this is related to changes in nupic.core by @chetan51, which are functionally equivalent to changing the random seed, and therefore this failure should not be cause for concern and we can fix suppress this failure by updating the NAB benchmark values.

See also [this JIRA](https://jira.numenta.com/browse/RES-143) on a related failure.

@rhyolight @scottpurdy

**Comment by scottpurdy** [comment]
Seems fine to update NAB benchmark values.

**Comment by SaganBolliger** [comment]
Great. PR #33 is open to address this issue.

**Comment by rhyolight** [comment]
Thanks @SaganBolliger
