### ISSUE TITLE
Regression test failure on clVerbosity

### ISSUE THREAD

**Issue by natoromano** [numenta/nupic.regression#43]
The parameter name appears in 2 tests which should be updated, and `clVerbosity` replaced with `verbosity`:

```
tests/anomaly/one_gym/rec_center_hourly_model_params.py
17:                                 'clVerbosity': 0,

tests/prediction/singleorder/rule_30_model_params.py
17:                                 'clVerbosity': 0,
```

**Comment by rhyolight** [comment]
Hopefully you can get regression tests running and passing locally by following the README. Ping me when you have a PR  (should be a simple find/replace) and I'll merge, then we'll wait to see if it passes in CI.
